### PR TITLE
Porting to angular cli

### PR DESCRIPTION
**Pull request by gise88**
Related https://github.com/zebzhao/Angular-QueryBuilder/issues/92

What I changed:
* Moved the QueryBuilder library into a new library project.
* Deleted the now useless files (i.e. index.ts -> also because of ng-packagr/ng-packagr#917) and webpack configs.
* Updated the demo app to the new version of Angular.
* Updated the scripts in the `package.json` of the lib and the demo in order to reflect the changes.

I tested it with `ng serve` and building the library in production version using both `ng build --prod` and `npm run build` and it for me it is fine.

I still have doubts on some scripts that you defined into the lib package.json so please review it carefully and test it.

Please, let me know if you are fine with my changes,
Gianluca

### CODE REVIEW

**Comment by gise88** [comment]
@zebzhao I've rebased it and clean the commits. 

I am waiting for this merge to create a new PR that introduce the possibility to style the invalid rules as well (and not only the rulesets): https://github.com/gise88/Angular-QueryBuilder/tree/style-for-invalid-rule

**Comment by zebzhao** [comment]
Thanks for this! Can I change the Angular version back down to 6, I'm worried about compatibility with people not using the latest version of Angular.

**Comment by gise88** [comment]
Sure, no problem. Do what you prefer. 😄 I mean, it is your library.

Just to clarify, I upgraded the Angular version of the library from 4.0 to 6.0 and from 6.0 to 8.0 of the demo app.
I don't think the people are interested about the version of the demo application. Indeed, I think it is remarkable the fact that the demo application works fine with the latest version of Angular.

Do you think is really needed this change?

However, I am open to your PR.. I can do it by myself but only when they get rid of various commitments at work.
Just let me know if you want do it by yourself or you will wait for my change.

**Comment by SebastianStehle** [comment]
I am thinking about making a few contributions because I need this for my headless CMS: https://squidex.io/

But I would need angular8. 

My contribution ideas are:

1. Support optional display names for values, e.g. when you want to check a reference you would use the id of the reference as value and a display name that represents the referenced entity for the UI.

2. Performance optimizations. I have no numbers about that, but I see a lot of "bad" practices in code, e.g. calculating values from the template. If we split up the component into small parts and calculate values when something changes we can probably improve performance a lot.

3. Personally I think that the buttons to create new rules or rulesets are placed in a strange way, I would expect to see them at the end of the list.

**Comment by pcurrivan** [comment]
FYI due to the recently accepted PR, you have no choice but to bump the devDependencies to 8.0.0 and the peerDependencies to 7.0.0.

See:
https://next.angular.io/guide/static-query-migration#can-i-update-my-library-to-version-8-by-adding-the-static-flag-to-view-queries-while-still-being-compatible-with-angular-version-7-apps
https://github.com/angular/angular/issues/30654#issuecomment-495642339

**Pull request closed without merging**
